### ISSUE TITLE
Nothing works after update to version 2.5.1

### ISSUE THREAD

**Issue by Flodu31** [flobz/psacc-ha#8]
Nothing works. Tried a uninstall/reinstall, with reauth, etc, but have the following error message:

```
Containerised psa_car_controller loading...
/usr/local/lib/python3.7/dist-packages/dash_bootstrap_components/_table.py:5: UserWarning: 
The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`
  import dash_html_components as html
2021-09-21 14:22:15,004 :: INFO :: save config change
2021-09-21 14:22:15,530 :: INFO :: ["{'vin': 'VR3U', 'vehicle_id': '', 'label': 'e-2008', 'brand': 'Peugeot', 'abrp_name': 'peugeot:e2008:20:48', 'battery_power': 46, 'fuel_capacity': 0, 'max_elec_consumption': 70, 'max_fuel_consumption': 0}"]
2021-09-21 14:22:15,854 :: INFO :: save config change
Traceback (most recent call last):
  File "/psa_car_controller/server.py", line 15, in <module>
    conf.load_app()
  File "/psa_car_controller/libs/config.py", line 103, in load_app
    self.start_remote_control()
  File "/psa_car_controller/libs/config.py", line 63, in start_remote_control
    self.myp.start_mqtt()
  File "/psa_car_controller/my_psacc.py", line 341, in start_mqtt
    self.mqtt_client.connect(MQTT_SERVER, 8885, 60)
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 1104, in reconnect
    sock.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)
```
Any idea?
Thanks.
Florent

**Comment by flobz** [comment]
It works for me.... The error mean that the PSA MQTT server use a  self signed certificate in certificate chain. It's not a problem from the app... It can be a MITM atack also.

**Comment by Flodu31** [comment]
Strange. Restored with image version 2.5.0, no issue.

**Comment by flobz** [comment]
Try again the 2.5.1, it was maybe a temporary issue.
